Module 3 home task has been completed.
Adenmin/DQE-Python-Run5 pull request #3
Opened 2022-02-06 07:12 UTC by Adenmin

2022-02-07 17:11 UTC, romkabauer requested changes

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +lines = {k: basicString[k] for k in lines}
What if we get another string as input? Function "enumerate" can help here

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +lines = {k: v.split(".") for k, v in lines.items()}
Maybe use re.split and some enhanced regexp to find sentences independently from text lines? We are not sure about the quality of the whole text, maybe some \ns are between sentences

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +additionalSentence = " ".join(last_words).capitalize()
In most of the real cases we will be not sure about the structure of the text. I mean headers, paragraphs etc. Let's try to build regexp for whole text to catch last words in every sentence, based on the "business requirement" that every "." is the end of the sentence.

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +mainText[3].append(additionalSentence)
I think it should be 2 in the index:)

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +        v[i] = v[i].replace("fix\u201Ciz\u201D", "fix \u201Ciz\u201D")  # missing space in Fix“iz”
It is not necessary to fix all misspellings according to the task. Only "iz" -> "is". I also suggest to apply re.sub on the whole text.

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +fullText = header
Try {**dict1, **dict2} if you use python 3.5+. It will be more readable. And better focus on sentences, because we are not sure about lines, but for sentences we have "business requirement" - they are splited by ".".

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +fourthParagraph = " ".join(fullText[4])
If we have 1 million lines? :)

2022-02-07 17:11 UTC, romkabauer commented on module3/string-object.py
> +finalText = finalText.replace("87", str(whitespaceCount))
You can just print the number outside the normalized text, as a separate line

2022-02-08 08:37 UTC, Adenmin commented on module3/string-object.py
> +lines = {k: basicString[k] for k in lines}
Fixed by enumerate.

2022-02-08 08:37 UTC, Adenmin commented on module3/string-object.py
> +lines = {k: v.split(".") for k, v in lines.items()}
Will be fixed as a part of module 4

2022-02-08 08:37 UTC, Adenmin commented on module3/string-object.py
> +additionalSentence = " ".join(last_words).capitalize()
Will be fixed as a part of module 4

2022-02-08 08:38 UTC, Adenmin commented on module3/string-object.py
> +mainText[3].append(additionalSentence)
Sure, fixed :)

2022-02-08 08:38 UTC, Adenmin commented on module3/string-object.py
> +        v[i] = v[i].replace("fix\u201Ciz\u201D", "fix \u201Ciz\u201D")  # missing space in Fix“iz”
Based on the results of the Q&A session, it was decided that these are mandatory cases for fixing. 
As an example of using unicode character IDs.

2022-02-08 08:38 UTC, Adenmin commented on module3/string-object.py
> +fullText = header
Fixed.

2022-02-08 08:38 UTC, Adenmin commented on module3/string-object.py
> +fourthParagraph = " ".join(fullText[4])
Will be fixed as a part of module 4

2022-02-08 08:38 UTC, Adenmin commented on module3/string-object.py
> +finalText = finalText.replace("87", str(whitespaceCount))
Fixed.

2022-02-12 12:13 UTC, merged