Module 7 home task has been completed.
Adenmin/DQE-Python-Run5 pull request #7
Opened 2022-02-27 13:21 UTC by Adenmin

2022-03-04 07:50 UTC, romkabauer commented on module5/NewsFeedStatistic.py
> +            for word, count in self.__get_world_statistic().items():
I think items is working not properly on arabic keys... It creates corteges with values as part of cortege with index = 0 and key as part of cortege with index = 1. That is why csv file will return bad data... I think we need to handle this situation somehow

2022-03-04 08:15 UTC, romkabauer requested changes

2022-03-04 08:15 UTC, romkabauer commented on module5/NewsFeedStatistic.py
> +            for word, count in self.__get_world_statistic().items():
I think items is working not properly on arabic keys... It creates corteges with values as part of cortege with index = 0 and key as part of cortege with index = 1. That is why csv file will return bad data... I think we need to handle this situation somehow

2022-03-04 08:15 UTC, romkabauer commented on module5/NewsFeedStatistic.py
> +                writer.writerow({'letter': letter,
I think this function is also work with arabic not properly.. Please check how we can handle it properly.

2022-03-09 14:51 UTC, Adenmin commented on module5/NewsFeedStatistic.py
> +            for word, count in self.__get_world_statistic().items():
This looks like a display bug. 
If we create csv file by csv.writer and read this file by csv.reader or csv.DictReader, then everything will work correctly.

2022-03-09 14:51 UTC, Adenmin commented on module5/NewsFeedStatistic.py
> +                writer.writerow({'letter': letter,
Additional plugins for PyCharm also display the data in the file correctly.
![image](https://user-images.githubusercontent.com/8178906/157465697-dc67fb3d-67c8-4dda-b7be-a1db56a6c718.png)

2022-03-10 12:35 UTC, romkabauer commented on module5/NewsFeedStatistic.py
> +            for word, count in self.__get_world_statistic().items():
Yes, it's a feature of readers, we need to specify that data sample have arabic characters to read it properly. So code is working as expected. Will close thread.

2022-03-10 12:35 UTC, romkabauer commented on module5/NewsFeedStatistic.py
> +                writer.writerow({'letter': letter,
Yes, it's a feature of readers, we need to specify that data sample have arabic characters to read it properly. So code is working as expected. Will close thread.

2022-03-10 12:35 UTC, merged